import type {SupabaseClient} from '@supabase/supabase-js';
import type {GridContentRating,GridAgeBand} from './GridContentAccess';
export interface GridSocialProfile{user_id:string;age_band:GridAgeBand;gender_identity:string;pronouns:string;orientation:string;profile_privacy:string;friend_privacy:string;follow_privacy:string;online_status_privacy:string;voice_privacy:string;}
export class GridSocialService{
  constructor(private readonly client:SupabaseClient){}
  async preferences(){const {data,error}=await this.client.from('grid_account_social').select('*').maybeSingle();if(error)throw error;return data as GridSocialProfile|null;}
  async savePreferences(input:Omit<GridSocialProfile,'user_id'>){const {data,error}=await this.client.rpc('grid_social_set_preferences',{p_age_band:input.age_band,p_gender_identity:input.gender_identity,p_pronouns:input.pronouns,p_orientation:input.orientation,p_profile_privacy:input.profile_privacy,p_friend_privacy:input.friend_privacy,p_follow_privacy:input.follow_privacy,p_online_status_privacy:input.online_status_privacy,p_voice_privacy:input.voice_privacy});if(error)throw error;return data as GridSocialProfile;}
  async canAccess(rating:GridContentRating){const {data,error}=await this.client.rpc('grid_age_band_allowed',{required_rating:rating});if(error)throw error;return Boolean(data);}
  async searchPeople(query:string){const q=query.replace(/^@/,'').trim();if(!q)return [];const {data,error}=await this.client.from('profiles').select('id,handle,display_name,avatar_image_url').ilike('handle','%'+q+'%').limit(20);if(error)throw error;const rows=(data??[]).filter((x:any)=>x.id);const ids=rows.map((x:any)=>x.id);const {data:presence}=ids.length?await this.client.from('grid_account_presence').select('user_id,online,last_seen_at').in('user_id',ids):{data:[]};const map=new Map((presence??[]).map((x:any)=>[x.user_id,x]));return rows.map((x:any)=>({...x,online:Boolean(map.get(x.id)?.online)}));}\n  async categories(){const {data,error}=await this.client.from('grid_forum_categories').select('*').order('label');if(error)throw error;return data??[];}
  async topics(categoryId?:string){let q=this.client.from('grid_forum_topics').select('*').order('updated_at',{ascending:false});if(categoryId)q=q.eq('category_id',categoryId);const {data,error}=await q.limit(60);if(error)throw error;const rows=data??[];const allowed=await Promise.all(rows.map(async (x:any)=>({x,ok:await this.canAccess(x.content_rating as GridContentRating)})));return allowed.filter(x=>x.ok).map(x=>x.x);}
  async posts(topicId:number){const {data,error}=await this.client.from('grid_forum_posts').select('*').eq('topic_id',topicId).order('created_at');if(error)throw error;const rows=data??[];const allowed=await Promise.all(rows.map(async (x:any)=>({x,ok:await this.canAccess(x.content_rating as GridContentRating)})));return allowed.filter(x=>x.ok).map(x=>x.x);}
  async createTopic(categoryId:string,title:string,description:string,rating:GridContentRating='E'){const ok=await this.canAccess(rating);if(!ok)throw new Error('Your account cannot create content at this rating.');const {data,error}=await this.client.from('grid_forum_topics').insert({category_id:categoryId,title,description,content_rating:rating,created_by_user:(await this.client.auth.getUser()).data.user?.id}).select().single();if(error)throw error;return data;}
  async createPost(topicId:number,body:string,rating:GridContentRating='E'){const ok=await this.canAccess(rating);if(!ok)throw new Error('Your account cannot post at this rating.');const {data,error}=await this.client.from('grid_forum_posts').insert({topic_id:topicId,body,content_rating:rating,author_user:(await this.client.auth.getUser()).data.user?.id}).select().single();if(error)throw error;return data;}
  async like(postId:number){const {error}=await this.client.from('grid_forum_likes').upsert({post_id:postId,user_id:(await this.client.auth.getUser()).data.user?.id});if(error)throw error;}
  async toggleLike(postId:number){const uid=(await this.client.auth.getUser()).data.user?.id;const {data}=await this.client.from('grid_forum_likes').select('post_id').eq('post_id',postId).eq('user_id',uid).maybeSingle();if(data){await this.unlike(postId);return false;}await this.like(postId);return true;}
  async unlike(postId:number){const {error}=await this.client.from('grid_forum_likes').delete().eq('post_id',postId).eq('user_id',(await this.client.auth.getUser()).data.user?.id);if(error)throw error;}
  async connect(targetId:string,kind:'friend'|'follow'){const {data,error}=await this.client.from('grid_social_connections').upsert({requester_id:(await this.client.auth.getUser()).data.user?.id,target_id:targetId,kind,status:kind==='friend'?'pending':'active'}).select().single();if(error)throw error;return data;}
  async setPresence(online:boolean){const {data,error}=await this.client.rpc('grid_set_presence',{p_online:online});if(error)throw error;return data;}
  async disconnect(targetId:string,kind:'friend'|'follow'){const {error}=await this.client.from('grid_social_connections').delete().eq('requester_id',(await this.client.auth.getUser()).data.user?.id).eq('target_id',targetId).eq('kind',kind);if(error)throw error;}
}
