import type {GridSocialService} from '../social/GridSocialService';
import type {GridContentRating} from '../social/GridContentAccess';
export function mountGridForumPanel(social:GridSocialService){
 const root=document.createElement('section');root.className='grid-social-overlay';root.innerHTML='<div class="grid-social-card"><button class="grid-social-close">×</button><div class="grid-social-kicker">GRID WORLD // COMMUNITY</div><h2>FORUMS</h2><div class="grid-forum-layout"><aside id="gf-cats"></aside><main><div id="gf-topics"></div><div id="gf-posts"></div></main></div></div>';document.body.appendChild(root);
 const cats=root.querySelector('#gf-cats')!,topics=root.querySelector('#gf-topics')!,posts=root.querySelector('#gf-posts')!;
 let category='welcome',topic:number|null=null;
 const close=()=>root.classList.remove('open');
 root.querySelector<HTMLButtonElement>('.grid-social-close')!.onclick=close;
 async function renderCats(){const rows=await social.categories();cats.innerHTML=rows.map((x:any)=>'<button class="gf-cat '+(x.id===category?'active':'')+'" data-cat="'+x.id+'"><b>'+x.label+'</b><small>'+x.content_rating+'</small><span>'+x.description+'</span></button>').join('');cats.querySelectorAll<HTMLButtonElement>('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat!;topic=null;void render();});}
 async function renderTopics(){const rows=await social.topics(category);topics.innerHTML='<div class="gf-toolbar"><b>TOPICS</b><button id="gf-new">NEW TOPIC</button></div>'+rows.map((x:any)=>'<button class="gf-topic" data-topic="'+x.id+'"><strong>'+x.title+'</strong><small>'+x.content_rating+' · '+new Date(x.updated_at).toLocaleString()+'</small><span>'+x.description+'</span></button>').join('');topics.querySelectorAll<HTMLButtonElement>('[data-topic]').forEach(b=>b.onclick=()=>{topic=Number(b.dataset.topic);void renderPostView();});root.querySelector<HTMLButtonElement>('#gf-new')!.onclick=async()=>{const title=prompt('Topic title?');if(!title)return;try{await social.createTopic(category,title,'Community-created topic','E');await renderTopics();}catch(e){alert(e instanceof Error?e.message:'Could not create topic.');}};}
 async function renderPostView(){if(!topic){posts.innerHTML='<div class="gf-empty">Select a topic to read the conversation.</div>';return;}const rows=await social.posts(topic);posts.innerHTML='<div class="gf-toolbar"><b>CONVERSATION</b><button id="gf-reply">REPLY</button></div>'+rows.map((x:any)=>'<article class="gf-post"><header><b>'+ (x.author_npc?'NPC':'GRID TRAVELER')+'</b><small>'+new Date(x.created_at).toLocaleString()+'</small></header><p>'+escapeHtml(x.body)+'</p><footer><span>'+x.content_rating+'</span><button data-like="'+x.id+'">♡ LIKE</button></footer></article>').join('');root.querySelector<HTMLButtonElement>('#gf-reply')!.onclick=async()=>{const body=prompt('Write your reply');if(!body)return;try{await social.createPost(topic!,body,'E');await renderPostView();}catch(e){alert(e instanceof Error?e.message:'Could not post.');}};posts.querySelectorAll<HTMLButtonElement>('[data-like]').forEach(b=>b.onclick=async()=>{await social.like(Number(b.dataset.like));b.textContent='♥ LIKED';});}
 async function render(){await renderCats();await renderTopics();await renderPostView();}
 function escapeHtml(s:string){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
 return {open:()=>{root.classList.add('open');void render();},close};
}
