import type { GridAuthService, GridAccountProfile } from '../auth/GridAuthService';

export function mountGridAuthPanel(auth:GridAuthService,onProfile:(profile:GridAccountProfile)=>void){
  const root=document.createElement('section'); root.className='grid-auth-overlay';
  root.innerHTML='<div class="grid-auth-card"><button class="grid-auth-close" type="button">×</button><div class="grid-auth-kicker">GRID WORLD IDENTITY</div><h2>JOIN THE GRID</h2><p class="grid-auth-note">Your email authenticates your account. Your public identity is your handle and display name; your full name is stored separately according to your privacy choice.</p><div class="grid-auth-tabs"><button data-mode="login">LOGIN</button><button data-mode="join">JOIN</button><button data-mode="profile">PROFILE</button></div><div class="grid-auth-body"></div><div class="grid-auth-status"></div></div>';
  document.body.appendChild(root);
  const body=root.querySelector<HTMLDivElement>('.grid-auth-body')!,status=root.querySelector<HTMLDivElement>('.grid-auth-status')!;
  let mode='login';
  function render(){
    if(mode==='login') body.innerHTML='<label>Email<input id="ga-email" type="email" autocomplete="email"></label><label>Password<input id="ga-password" type="password" autocomplete="current-password"></label><button class="grid-auth-primary" id="ga-submit">LOGIN</button><button class="grid-auth-secondary" id="ga-reset">SEND PASSWORD RESET</button><p>Passwords are handled by Supabase Auth, not Grid World.</p>';
    else if(mode==='join') body.innerHTML='<label>Email<input id="ga-email" type="email" autocomplete="email"></label><label>Password<input id="ga-password" type="password" minlength="12" autocomplete="new-password"></label><p class="grid-auth-note">Use a unique password of at least 12 characters. Email confirmation is part of the production join flow.</p><button class="grid-auth-primary" id="ga-submit">CREATE ACCOUNT</button>';
    else body.innerHTML='<div class="grid-name-grid"><label>First name<input id="ga-first" maxlength="60"></label><label>Middle name <small>optional</small><input id="ga-middle" maxlength="60"></label><label>Last name<input id="ga-last" maxlength="60"></label><label>Handle <small>3–32 chars</small><input id="ga-handle" maxlength="32" placeholder="yourname"></label><label>Display name<input id="ga-display" maxlength="80"></label><label>Name visibility<select id="ga-vis"><option value="display_only">Display name only</option><option value="public">Full name public</option><option value="private">Full name private</option></select></label></div><p class="grid-auth-note">Handles are globally unique. If one is taken, choose another handle; display names may be shared.</p><button class="grid-auth-primary" id="ga-profile">SAVE PROFILE</button><div class="grid-land-actions"><select id="ga-world"><option>HARBOR</option><option>GARDENS</option><option>ARTS</option><option>CITADEL</option><option>WILDS</option><option>SKYROOT</option></select><button id="ga-land">CLAIM FREE STARTER LAND</button><button id="ga-charter">EARN A WORLD CHARTER</button><button id="ga-starter">CLAIM OMNI BANK STARTER</button><button id="ga-signout">SIGN OUT</button></div>';
    const submit=body.querySelector<HTMLButtonElement>('#ga-submit'); if(submit) submit.onclick=async()=>{status.textContent='Working…';try{if(mode==='login'){const r=await auth.signIn((body.querySelector<HTMLInputElement>('#ga-email')!).value,(body.querySelector<HTMLInputElement>('#ga-password')!).value);if(r.error)throw r.error;status.textContent=r.data.user?'Logged in.':'Check your credentials.';mode='profile';render();}else{const r=await auth.signUp((body.querySelector<HTMLInputElement>('#ga-email')!).value,(body.querySelector<HTMLInputElement>('#ga-password')!).value);if(r.error)throw r.error;status.textContent=r.data.session?'Account created and signed in.':'Account created. Check your email to confirm it, then log in.';mode=r.data.session?'profile':'login';render();}}catch(e){status.textContent=e instanceof Error?e.message:'Authentication failed.';}};
    const reset=body.querySelector<HTMLButtonElement>('#ga-reset'); if(reset) reset.onclick=async()=>{try{const email=(body.querySelector<HTMLInputElement>('#ga-email')!).value;const r=await auth.resetPassword(email);if(r.error)throw r.error;status.textContent='Password reset email requested.';}catch(e){status.textContent=e instanceof Error?e.message:'Password reset request failed.';}};
    const signout=body.querySelector<HTMLButtonElement>('#ga-signout'); if(signout) signout.onclick=async()=>{const r=await auth.signOut();if(r.error){status.textContent=r.error.message;return;}status.textContent='Signed out.';root.classList.remove('open');};
    const save=body.querySelector<HTMLButtonElement>('#ga-profile'); if(save) save.onclick=async()=>{status.textContent='Saving…';try{const result=await auth.completeProfile({firstName:(body.querySelector<HTMLInputElement>('#ga-first')!).value,middleName:(body.querySelector<HTMLInputElement>('#ga-middle')!).value,lastName:(body.querySelector<HTMLInputElement>('#ga-last')!).value,handle:(body.querySelector<HTMLInputElement>('#ga-handle')!).value,displayName:(body.querySelector<HTMLInputElement>('#ga-display')!).value,nameVisibility:(body.querySelector<HTMLSelectElement>('#ga-vis')!).value});const p=await auth.profile();if(p)onProfile(p);status.textContent=(result as any)?.handle+' secured.';}catch(e){status.textContent=e instanceof Error?e.message:'Profile update rejected.';}};
  }
  root.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode!;render();});
  root.querySelector<HTMLButtonElement>('.grid-auth-close')!.onclick=()=>root.classList.remove('open');
  render();
  async function open(next='login'){mode=next;root.classList.add('open');render();if(mode==='profile'){try{const p=await auth.profile();if(p){(body.querySelector<HTMLInputElement>('#ga-first')!).value=p.first_name??'';(body.querySelector<HTMLInputElement>('#ga-middle')!).value=p.middle_name??'';(body.querySelector<HTMLInputElement>('#ga-last')!).value=p.last_name??'';(body.querySelector<HTMLInputElement>('#ga-handle')!).value=(p.handle??'').replace(/^@/,'');(body.querySelector<HTMLInputElement>('#ga-display')!).value=p.display_name??'';(body.querySelector<HTMLSelectElement>('#ga-vis')!).value=p.name_visibility??'display_only';}}catch{}}}return {open,close:()=>root.classList.remove('open')};
}