import type {GridOperatorService} from '../operator/GridOperatorService';

export function mountGridOperatorPanel(operator:GridOperatorService){
 const root=document.createElement('aside');root.className='grid-operator-dock';root.innerHTML='<div class="go-head"><div><span>GRID OPERATOR</span><b>● ONLINE</b></div><button aria-label="Close">×</button></div><div class="go-alerts"></div><div class="go-messages" aria-live="polite"></div><form class="go-form"><input aria-label="Ask Grid Operator" maxlength="4000" placeholder="Ask about Grid World, rules, safety, accounts…"><button>ASK</button></form><div class="go-foot"><button data-verify>VERIFY ACCOUNT</button><small>Operator AI · policy-aware · human review available</small></div></aside>';
 document.body.appendChild(root);
 const messages=root.querySelector<HTMLDivElement>('.go-messages')!,alerts=root.querySelector<HTMLDivElement>('.go-alerts')!,input=root.querySelector<HTMLInputElement>('input')!,form=root.querySelector<HTMLFormElement>('form')!;
 const add=(who:string,text:string)=>{const d=document.createElement('div');d.className='go-msg '+who;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;};
 async function refresh(){try{const c=await operator.context();const cases=c.context.cases||[];alerts.innerHTML=cases.length?cases.map((x:any)=>'<button class="go-alert" data-case="'+x.id+'"><b>'+String(x.severity).toUpperCase()+'</b> '+x.title+'<small>'+x.summary+'</small></button>').join(''):'<div class="go-clear">✓ No open account issues detected.</div>';}catch{alerts.innerHTML='<div class="go-clear">Operator account analysis is temporarily unavailable.</div>';}}
 form.onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;add('user',q);input.value='';try{const r=await operator.chat(q);add('operator',r.answer);await refresh();}catch{add('operator','I can’t reach the Operator service right now. Please try again shortly.');}};
 root.querySelector<HTMLButtonElement>('.go-head button')!.onclick=()=>root.classList.remove('open');
 root.querySelector<HTMLButtonElement>('[data-verify]')!.onclick=async()=>{const status=await operator.verificationStatus();const code=prompt('Grid Codeword: create or enter the private codeword you chose for your account.');if(code===null)return;const recovery=prompt('Grid Recovery Phrase: create or enter a separate phrase you can securely recover.');if(recovery===null)return;if(status.enrolled){const result=await operator.verify(code,recovery);alert(result.verified?'Three-factor verification complete.':'Verification failed.');}else{try{await operator.enroll(code,recovery);alert('Verification enrolled: verified email + Grid Codeword + Grid Recovery Phrase.');}catch(e){alert(e instanceof Error?e.message:'Verification enrollment failed.');}}};
 void refresh(); add('operator','Hello. I’m Grid Operator. I can explain Grid World rules, account controls, safety, moderation, and world systems. If an account issue needs attention, I’ll tell you what I found and what you can do next.');
 return {open:()=>{root.classList.add('open');void refresh();},close:()=>root.classList.remove('open')};
}