import type {GridSocialService} from '../social/GridSocialService';
import {mountGridForumPanel} from './GridForumPanel';

function accountAge(createdAt:string){const days=Math.max(0,Math.floor((Date.now()-Date.parse(createdAt))/86400000));if(days<1)return 'NEW ACCOUNT · < 1 DAY';if(days<30)return 'ACCOUNT AGE · '+days+' DAYS';const years=Math.floor(days/365);const months=Math.floor((days%365)/30);return 'ACCOUNT AGE · '+(years?years+'Y ':'')+months+'M';}
function avatarData(name:string){const safe=name.replace(/[^A-Za-z0-9 ]/g,'').slice(0,18)||'Traveler';const svg='<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#12283a"/><stop offset="1" stop-color="#51386f"/></linearGradient></defs><rect width="160" height="160" rx="80" fill="url(#g)"/><circle cx="80" cy="61" r="28" fill="#d8e4e8"/><path d="M37 139c5-35 24-52 43-52s38 17 43 52" fill="#d8e4e8"/><text x="80" y="151" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#71dfff">'+safe.toUpperCase()+'</text></svg>';return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);}
export function mountGridCommunityPanel(social:GridSocialService,identity:{displayName:string;id:string;createdAt:string}){
 const root=document.createElement('section');root.className='grid-social-overlay';root.innerHTML='<div class="grid-social-card grid-community-card"><button class="grid-social-close">×</button><div class="grid-social-kicker">GRID WORLD // SOCIAL</div><div class="gc-tabs"><button data-tab="profile">PROFILE</button><button data-tab="people">PEOPLE</button><button data-tab="privacy">PRIVACY</button><button data-tab="forums">FORUMS</button><button data-tab="voice">VOICE</button></div><div id="gc-body"></div></div>';document.body.appendChild(root);
 const body=root.querySelector<HTMLDivElement>('#gc-body')!;const forum=mountGridForumPanel(social);let current='profile';
 root.querySelector<HTMLButtonElement>('.grid-social-close')!.onclick=()=>{root.classList.remove('open');forum.close();};
 async function render(){
  if(current==='forums'){body.innerHTML='<div class="gc-forum-note">Forums are opened in the community layer.</div>';forum.open();return;}
  forum.close();
  if(current==='profile'){const p=await social.preferences();body.innerHTML='<div class="gc-profile"><img class="gc-avatar" src="'+avatarData(identity.displayName)+'"><div><h3>'+identity.displayName+'</h3><p>● ONLINE</p><small>'+accountAge(identity.createdAt)+'</small></div></div><div class="gc-note">Your Grid avatar is automatically represented by a starter identity image and can later be replaced by your saved avatar portrait.</div>';return;}
  if(current==='privacy'){const p=await social.preferences();const x=p??{age_band:'adult',gender_identity:'unspecified',pronouns:'unspecified',orientation:'private',profile_privacy:'public',friend_privacy:'friends',follow_privacy:'everyone',online_status_privacy:'everyone',voice_privacy:'everyone'};body.innerHTML='<div class="gc-form"><label>Account age band<select id="gc-age"><option value="child">Child</option><option value="teen">Teen</option><option value="adult">Adult</option></select></label><label>Gender identity<input id="gc-gender" value="'+x.gender_identity+'"></label><label>Pronouns<input id="gc-pronouns" value="'+x.pronouns+'"></label><label>Orientation <small>optional/private</small><input id="gc-orientation" value="'+x.orientation+'"></label><label>Profile privacy<select id="gc-profile"><option>public</option><option>friends</option><option>private</option></select></label><label>Friend requests<select id="gc-friend"><option>everyone</option><option>friends</option><option>no_one</option></select></label><label>Follow privacy<select id="gc-follow"><option>everyone</option><option>friends</option><option>no_one</option></select></label><label>Online status<select id="gc-online"><option>everyone</option><option>friends</option><option>no_one</option></select></label><label>Voice privacy<select id="gc-voice"><option>everyone</option><option>friends</option><option>no_one</option></select></label><button id="gc-save">SAVE PRIVACY</button></div>';for(const [id,val] of [['gc-age',x.age_band],['gc-profile',x.profile_privacy],['gc-friend',x.friend_privacy],['gc-follow',x.follow_privacy],['gc-online',x.online_status_privacy],['gc-voice',x.voice_privacy]])(body.querySelector('#'+id) as HTMLSelectElement).value=val as string;body.querySelector<HTMLButtonElement>('#gc-save')!.onclick=async()=>{await social.savePreferences({age_band:(body.querySelector('#gc-age') as HTMLSelectElement).value as any,gender_identity:(body.querySelector('#gc-gender') as HTMLInputElement).value,pronouns:(body.querySelector('#gc-pronouns') as HTMLInputElement).value,orientation:(body.querySelector('#gc-orientation') as HTMLInputElement).value,profile_privacy:(body.querySelector('#gc-profile') as HTMLSelectElement).value,friend_privacy:(body.querySelector('#gc-friend') as HTMLSelectElement).value,follow_privacy:(body.querySelector('#gc-follow') as HTMLSelectElement).value,online_status_privacy:(body.querySelector('#gc-online') as HTMLSelectElement).value,voice_privacy:(body.querySelector('#gc-voice') as HTMLSelectElement).value});alert('Privacy and identity settings saved.');};return;}
  if(current==='people'){body.innerHTML='<div class="gc-search"><input id="gc-search" placeholder="Search handle"><button id="gc-find">FIND</button></div><div id="gc-results"></div>';body.querySelector<HTMLButtonElement>('#gc-find')!.onclick=async()=>{const q=(body.querySelector<HTMLInputElement>('#gc-search')!).value.trim();const rows=await social.searchPeople(q);body.querySelector('#gc-results')!.innerHTML=rows.map((r:any)=>'<article class="gc-person"><img src="'+avatarData(r.display_name)+'"><div><b>'+r.display_name+'</b><small>@'+r.handle+' · '+(r.online?'● ONLINE':'○ OFFLINE')+'</small></div><button data-friend="'+r.id+'">ADD FRIEND</button><button data-follow="'+r.id+'">FOLLOW</button></article>').join('');body.querySelectorAll<HTMLButtonElement>('[data-friend]').forEach(b=>b.onclick=async()=>{b.textContent=(await social.toggleConnection(b.dataset.friend!,'friend'))?'UNFRIEND':'ADD FRIEND'});body.querySelectorAll<HTMLButtonElement>('[data-follow]').forEach(b=>b.onclick=async()=>{b.textContent=(await social.toggleConnection(b.dataset.follow!,'follow'))?'UNFOLLOW':'FOLLOW'});};return;}
  body.innerHTML='<div class="gc-note">Voice modification is optional. Use the microphone controls in-world to choose a supported voice preset; your raw microphone is never required to be published.</div>';
 }
 root.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{current=b.dataset.tab!;void render();});
 return {open:()=>{root.classList.add('open');void render();},close:()=>root.classList.remove('open')};
}