import * as THREE from 'three';
import type { EcologyWorld, EcologySnapshot } from './CreatureEcologySystem';
import { traversalHit, steerAround } from './TraversalSystem';
import type { WorldConsequenceSnapshot } from './WorldConsequenceSystem';
import { getWorlds } from './GridWorldRegistry';
import type { LivingWorldEventKind } from './GridLivingWorld';
import { hourOfDayFromDayFraction, resolveNpcRoutine, routinePhaseFor } from '../npc/NpcDailyRoutine';
import { createNPCProfile, type NPCProfileRecord } from './NPCProfile';
import { NPCRelationshipNetwork, type NPCRelationship } from './NPCRelationshipSystem';
import { NPCInventorySystem } from './NPCInventorySystem';
import { NPCJobProgressionSystem } from './NPCJobProgressionSystem';
import { GridMaterialDropSystem } from './GridMaterialDropSystem';
import { NPCProductionSystem } from './NPCProductionSystem';
import { NPCMarketSystem } from './NPCMarketSystem';
