import {GridSystemJobRunner} from './GridSystemJobs';
import {inspectGrid3D} from './Grid3DWatchdog';
import {inspectImageElement} from './GridAssetGuard';
export function installGridHealthMonitor(root:HTMLElement){
 const runner=new GridSystemJobRunner();
 const assetHealth=()=>((window as any).__GRID_ASSET_HEALTH__?.last??[]) as Array<{ok:boolean;url:string}>;
 runner.register({id:'3d.viewport',domain:'3D',name:'3D viewport watchdog',intervalMs:10000,run:async()=>{const r=inspectGrid3D(root);const isDiagnosticsPage=location.pathname.endsWith('/diagnostics.html');if(isDiagnosticsPage&&!r.canvasCount)return{status:'passed',message:'3D viewport not applicable on diagnostics surface'};return{status:r.healthy?'passed':'warning',message:r.healthy?'WebGL viewport healthy':`Canvas ${r.canvasCount}; sized=${r.hasSizedCanvas}; WebGL=${r.webgl}`}}});
 runner.register({id:'3d.context',domain:'3D',name:'3D context-loss watchdog',intervalMs:5000,run:async()=>{const lost=root.querySelectorAll('canvas[data-grid-context-lost="true"]').length;return{status:lost?'failed':'passed',message:lost?'WebGL context loss detected':'Renderer context stable'}}});
 runner.register({id:'imagery.registry',domain:'IMAGERY',name:'Critical asset registry',intervalMs:15000,run:async()=>{const h=assetHealth();const bad=h.filter(x=>!x.ok);return{status:bad.length?'failed':'passed',message:bad.length?`${bad.length} registered assets unavailable`:`${h.length} registered assets reachable`}}});
 runner.register({id:'imagery.loaded',domain:'IMAGERY',name:'Imagery watchdog',intervalMs:15000,run:async()=>{const imgs=[...document.images];const reports=await Promise.all(imgs.map(inspectImageElement));const bad=reports.filter(x=>x.status!=='loaded');return{status:bad.length?'warning':'passed',message:`${imgs.length-bad.length}/${imgs.length} imagery elements loaded`}}});
 runner.register({id:'routes.links',domain:'ROUTES',name:'Navigation watchdog',intervalMs:20000,run:async()=>{const links=[...document.querySelectorAll<HTMLAnchorElement>('a[href]')].filter(a=>a.href.startsWith(location.origin));const checks=await Promise.all(links.map(async a=>{try{return(await fetch(a.href,{method:'HEAD',cache:'no-store'})).ok}catch{return false}}));const bad=checks.filter(x=>!x).length;return{status:bad?'warning':'passed',message:`${links.length-bad}/${links.length} internal links reachable`}}});
 runner.register({id:'games.registry',domain:'GAMES',name:'Game registry watchdog',intervalMs:20000,run:async()=>{const links=[...document.querySelectorAll<HTMLAnchorElement>('a[href*="/game.html?game="]')];return{status:'passed',message:`${links.length} registered game links detected`}}});
 runner.register({id:'runtime.errors',domain:'CODE',name:'Runtime error watchdog',intervalMs:5000,run:async()=>{const errors=Number((window as any).__GRID_RUNTIME_ERRORS__??0);return{status:errors?'warning':'passed',message:errors?`${errors} runtime errors captured`:'No runtime errors captured'}}});
 runner.register({id:'performance.frame',domain:'LIVE',name:'Frame health watchdog',intervalMs:5000,run:async()=>{const now=performance.now();const prev=(window as any).__GRID_HEALTH_LAST_FRAME as number|undefined;(window as any).__GRID_HEALTH_LAST_FRAME=now;return{status:prev&&now-prev>800?'warning':'passed',message:prev&&now-prev>800?'Main-thread pause detected':'Client heartbeat stable'}}});
 runner.register({id:'security.guard',domain:'CODE',name:'Security guard watchdog',intervalMs:10000,run:async()=>{const q=document.querySelectorAll('[data-grid-quarantine="true"]').length;const insecure=location.protocol!=='https:'&&location.hostname!=='localhost';return{status:q||insecure?'warning':'passed',message:q?`${q} quarantined surfaces`:insecure?'Non-HTTPS runtime':'Transport security OK'}}});
 runner.register({id:'code.health',domain:'CODE',name:'Build analyzer report',intervalMs:30000,run:async()=>{try{const r=await fetch('/diagnostics/code-health.json?live='+Date.now(),{cache:'no-store'});if(!r.ok)return{status:'warning',message:'Analyzer report unavailable'};const j=await r.json();const c=j.checks||{};const bad=Object.values(c).some(v=>v===false);return{status:bad?'failed':'passed',message:bad?'Analyzer found a build health issue':'Analyzer checks passing'}}catch{return{status:'warning',message:'Analyzer report unavailable'}}}});
 runner.register({id:'live.signal',domain:'LIVE',name:'Live heartbeat',intervalMs:5000,run:async()=>({status:'passed',message:'Grid client heartbeat '+new Date().toISOString()})});
 let runtimeErrors=0;(window as any).__GRID_RUNTIME_ERRORS__=0;
 addEventListener('error',()=>{runtimeErrors++;(window as any).__GRID_RUNTIME_ERRORS__=runtimeErrors},{capture:true});
 addEventListener('unhandledrejection',()=>{runtimeErrors++;(window as any).__GRID_RUNTIME_ERRORS__=runtimeErrors});
 root.addEventListener('webglcontextlost',e=>{(e.target as HTMLCanvasElement).dataset.gridContextLost='true';e.preventDefault()},{capture:true});
 runner.startAll();(window as any).__GRID_HEALTH__=runner;return runner;
}