import {GRID_ASSETS,type GridAsset} from './GridAssetRegistry';
export interface GridAssetHealth{url:string;kind:string;ok:boolean;status:number;contentType:string;ms:number;error?:string}
const fallbackSvg=(label:string)=>'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 300"><rect width="800" height="300" fill="#07111b"/><path d="M0 250L180 150 330 220 500 90 800 230V300H0Z" fill="#0e2638"/><path d="M0 250L180 150 330 220 500 90 800 230" fill="none" stroke="#55e7ff" stroke-width="3"/><text x="32" y="48" fill="#71e7ff" font-family="monospace" font-size="18" letter-spacing="4">GRID VISUAL FALLBACK</text><text x="32" y="80" fill="#dffaff" font-family="monospace" font-size="14">'+label.replace(/[<>&"]/g,'')+'</text></svg>');
export function installGridAssetHealth(root:ParentNode=document){
 const repair=(img:HTMLImageElement)=>{if(img.dataset.gridAssetGuarded==='1')return;img.dataset.gridAssetGuarded='1';img.decoding='async';img.loading='eager';img.addEventListener('error',()=>{img.dataset.gridAssetState='failed';if(!img.dataset.gridFallback){img.dataset.gridFallback='1';img.src=fallbackSvg(img.alt||'Visual asset unavailable');}});img.addEventListener('load',()=>{img.dataset.gridAssetState='loaded';});if(img.complete)img.dataset.gridAssetState=img.naturalWidth>0?'loaded':'failed';};
 const scan=()=>root.querySelectorAll<HTMLImageElement>('img').forEach(repair);scan();
 const observer=new MutationObserver(scan);observer.observe(root,{subtree:true,childList:true});
 const preflight=async():Promise<GridAssetHealth[]>=>Promise.all(GRID_ASSETS.map(async(a:GridAsset)=>{const t=performance.now();try{const r=await fetch(a.url,{cache:'no-store',headers:{Accept:a.kind==='image'?'image/*':'*/*'}});return{url:a.url,kind:a.kind,ok:r.ok,status:r.status,contentType:r.headers.get('content-type')||'',ms:Math.round(performance.now()-t),...(r.ok?{}:{error:'HTTP '+r.status})};}catch(e){return{url:a.url,kind:a.kind,ok:false,status:0,contentType:'',ms:Math.round(performance.now()-t),error:String(e)}}}));
 (window as any).__GRID_ASSET_HEALTH__={assets:GRID_ASSETS,preflight};
 void preflight().then(results=>{const bad=results.filter(r=>!r.ok);document.documentElement.dataset.gridImagery=bad.length?'degraded':'healthy';document.documentElement.dataset.gridImageryFailures=String(bad.length);(window as any).__GRID_ASSET_HEALTH__.last=results;});
 return {preflight,assets:GRID_ASSETS};
}