import {createClient} from '@supabase/supabase-js'; import {SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,supabaseConfigured} from './persistence/config';
import './community-page.css';
const root=document.querySelector<HTMLDivElement>('#community-page')!,kind=root.dataset.kind; const sb=supabaseConfigured?createClient(SUPABASE_URL!,SUPABASE_PUBLISHABLE_KEY!):null;
async function load(){let rows:any[]=[]; if(sb){const q=kind==='meetups'?await sb.from('grid_meetups').select('*').in('status',['OPEN','CHECKIN','COMPLETE']).order('starts_at',{ascending:true}):await sb.from('grid_classifieds').select('*').eq('status','OPEN').order('created_at',{ascending:false}); rows=q.data||[];}
const emptyState = rows.length === 0 ? (
  kind === 'meetups'
    ? '<article class="empty"><b>No meetups scheduled yet</b><p>Grid World is in active development — community meetups open with the public launch. When they do: public venues only, exact addresses hidden until check-in, guardian-aware participation, and built-in reporting.</p><small>PLANNED · NOT YET LIVE</small></article>'
    : '<article class="empty"><b>The board is quiet</b><p>No open listings right now. Classifieds go live with the public launch — find, sell, trade, and hire with content ratings and platform moderation.</p><small>PLANNED · NOT YET LIVE</small></article>'
) : '';
root.innerHTML='<header><a href="/">GRID WORLD</a><span>'+ (kind==='meetups'?'SAFE IRL MEETUPS':'GRID CLASSIFIEDS')+'</span></header><main><div class="hero"><small>REAL-WORLD BRIDGE</small><h1>'+ (kind==='meetups'?'Meet safely.':'Find, sell, trade, hire.')+'</h1><p>'+ (kind==='meetups'?'Public venues, hidden exact addresses, check-in windows, guardian-aware participation, and reporting are built into the event model.':'A Craigslist-style community board for Grid users, with content ratings and platform moderation.')+'</p></div><section>'+emptyState+rows.map(x=>'<article><b>'+String(x.title)+'</b><small>'+String(x.venue_label||x.category||'Grid')+'</small><p>'+String(x.description||x.body||'')+'</p></article>').join('')+'</section></main>';} load();