import './docs.css';
const app=document.querySelector<HTMLDivElement>('#docs')!;
app.innerHTML=`
<main class="docs"><div class="eyebrow">GRID WORLD · DOCUMENTATION</div><h1>The platform<br><span>behind the Grid.</span></h1><p class="lead">Living documentation for the website, 3D client, creator platform, economy, identity, multiplayer, mobile direction, QR links and safety architecture.</p>
<section><h2>Product surfaces</h2><div class="cards"><article><b>Website</b><p>Discovery, profiles, communities, events, marketplace, economics, staff and documentation.</p></article><article><b>3D World</b><p>First Light, movement, HUD windows, chat, multiplayer presence, object profiles, build mode and Field discovery.</p></article><article><b>Mobile</b><p>Identity, chat, friends, inventory, wallet, events, Field routes, QR scanning and selected 3D experiences.</p></article><article><b>Creator</b><p>Primitive to building, materials, voxel sculpting, scripting, advanced geometry, publishing, versioning and permissions.</p></article></div></section>
<section><h2>Interaction contract</h2><ul><li>Primary navigation resolves to real sections or pages.</li><li>Style selector persists locally and exposes multiple visual languages.</li><li>Social composer, reactions, share, Marketplace, social surfaces and profile controls have prototype behavior.</li><li>QR opens a camera scanner where supported, with a manual-link fallback.</li><li>Economics, Staff and Documentation are first-class pages.</li></ul></section>
<section><h2>Grid Currency</h2><p>Grid Currency is currently a simulated internal economy. It is not USD, not a bank deposit, and not redeemable for cash. The server model uses currency definitions, rate snapshots, user wallets, immutable ledger transactions and ledger entries. Row-level security limits wallet and ledger reads to the owning authenticated user.</p><p>External payment providers remain a separate integration boundary. Real-world financial functionality requires appropriate identity, payments, tax, consumer-protection and money-transmission review before production.</p></section>
<section><h2>Security boundaries</h2><ul><li>No service-role keys in browser code.</li><li>Balances are not trusted from local storage.</li><li>Ledger records are append-oriented; reversals should be new transactions.</li><li>Idempotency keys protect retry safety.</li><li>Row-level security is enabled on exposed economic tables.</li><li>External payout providers remain server-side integrations.</li></ul></section>
<section><h2>Ten Grid currencies</h2><div class="table"><div><b>GRD</b><span>Grid · core</span></div><div><b>LUM</b><span>Lumen · creator</span></div><div><b>SPK</b><span>Spark · creator</span></div><div><b>RUT</b><span>Root · resource</span></div><div><b>TDE</b><span>Tide · community</span></div><div><b>ECO</b><span>Echo · community</span></div><div><b>FRG</b><span>Forge · creator</span></div><div><b>ORB</b><span>Orbit · event</span></div><div><b>AET</b><span>Aether · governance</span></div><div><b>MRD</b><span>Meridian · collectible</span></div></div></section>
<section><h2>World and creator contracts</h2><p>World → Region → Chunk/Voxel Volume → Player Object. Objects can carry profiles, canonical geometry, render LODs, physics proxies and optional voxel/SDF data. Edits should become versioned operations with permissions, collaboration, undo history and authoritative server validation.</p></section>
<footer><a href="/">← Grid World</a><span>Documentation evolves with the platform.</span></footer></main>`;
