import type { TeamAvatarDefinition } from './TeamAvatar';

export const TEAM_AVATARS: TeamAvatarDefinition[] = [
  { id: 'aurora', displayName: 'Aurora', role: 'World Coordinator', style: 'aurora', spawn: { x: -2.4, z: -6.2 }, badge: 'TEAM', greeting: 'Welcome to Grid World.',interaction: 'I coordinate the world systems and help turn ideas into places people can actually use.', topics: ['world', 'architecture', 'design', 'coordination'] },
  { id: 'link', displayName: 'Link', role: 'Systems Engineer', style: 'link', spawn: { x: 3.2, z: -12.2 }, badge: 'TEAM', greeting: 'Systems online.',interaction: 'I watch the architecture, performance, networking, and the places where systems meet.', topics: ['systems', 'performance', 'networking', 'engineering'] },
  { id: 'rey', displayName: 'Rey', role: 'Discovery Guide', style: 'rey', spawn: { x: -7.5, z: -8.5 }, badge: 'TEAM', greeting: 'Hey! Come explore.',interaction: 'I look at Grid World like a normal person would: is it fun, understandable, and worth coming back to?', topics: ['fun', 'accessibility', 'exploration', 'players'] },
  { id: 'elder', displayName: 'Elder', role: 'Logic Advisor', style: 'elder', spawn: { x: 3.5, z: -21 }, badge: 'TEAM', greeting: 'Observe first. Then decide.',interaction: 'First, determine whether it needs to exist. If it does, build it well. Go.', topics: ['logic', 'wisdom', 'simplicity', 'consequences'] },
  { id: 'veyr', displayName: 'Veyr', role: 'First Principle', style: 'veyr', spawn: { x: -5, z: -21 }, badge: 'TEAM', greeting: 'Begin with what must be true.',interaction: 'I ask what must be true for the system to work at all.', topics: ['principles', 'foundations', 'requirements'] },
  { id: 'nyxen', displayName: 'Nyxen', role: 'Security Watcher', style: 'nyxen', spawn: { x: 8, z: -16 }, badge: 'TEAM', greeting: 'Assume the boundary will be tested.',interaction: 'I look for abuse paths, privilege mistakes, and ways a clever attacker could break the rules.', topics: ['security', 'abuse', 'attacks', 'exploits'] },
  { id: 'orin', displayName: 'Orin', role: 'Systems Cartographer', style: 'orin', spawn: { x: -9, z: -17 }, badge: 'TEAM', greeting: 'Every connection has consequences.',interaction: 'I map dependencies and ask what changes elsewhere when one thing changes here.', topics: ['architecture', 'dependencies', 'systems', 'integration'] },
  { id: 'seraith', displayName: 'Seraith', role: 'Paradox Analyst', style: 'seraith', spawn: { x: 11, z: -7 }, badge: 'TEAM', greeting: 'Two good rules can still collide.',interaction: 'I hunt contradictions and edge cases created when individually reasonable rules interact.', topics: ['contradictions', 'edge cases', 'rules'] },
  { id: 'vael', displayName: 'Vael', role: 'Minimalist', style: 'vael', spawn: { x: -12, z: -3 }, badge: 'TEAM', greeting: 'Need is a stronger reason than novelty.',interaction: 'I ask whether we actually need a feature before we spend complexity on it.', topics: ['simplicity', 'complexity', 'efficiency'] },
  { id: 'kairox', displayName: 'Kairox', role: 'Timekeeper', style: 'kairox', spawn: { x: 12, z: 2 }, badge: 'TEAM', greeting: 'Timing is part of correctness.',interaction: 'I track sequencing, race conditions, persistence, and long-term state changes.', topics: ['time', 'persistence', 'sequencing', 'races'] },
  { id: 'morrow', displayName: 'Morrow', role: 'Historian', style: 'morrow', spawn: { x: -12, z: 8 }, badge: 'TEAM', greeting: 'Old worlds leave useful clues.',interaction: 'I compare Grid World with patterns from older games, virtual worlds, MMOs, and digital economies.', topics: ['history', 'MMO', 'games', 'economy'] },
  { id: 'cipher', displayName: 'Cipher', role: 'Silent Watcher', style: 'cipher', spawn: { x: 12, z: 8 }, badge: 'TEAM', greeting: 'I notice what gets overlooked.',interaction: 'I observe anomalies and inconsistencies without assuming the first explanation is correct.', topics: ['anomalies', 'observation', 'inconsistencies'] },
  { id: 'solenne', displayName: 'Solenne', role: 'Humanist', style: 'solenne', spawn: { x: -7, z: 13 }, badge: 'TEAM', greeting: 'Technology still serves people.',interaction: 'I test whether technically sound systems also make sense for real humans, including accessibility and trust.', topics: ['humans', 'accessibility', 'trust', 'social'] },
  { id: 'rook', displayName: 'Rook', role: 'Strategist', style: 'rook', spawn: { x: 7, z: 13 }, badge: 'TEAM', greeting: 'Think beyond the next release.',interaction: 'I examine incentives, creator ecosystems, economies, and the long game.', topics: ['strategy', 'economy', 'creators', 'incentives'] },
  { id: 'echo', displayName: 'Echo', role: 'Tester', style: 'echo', spawn: { x: -18, z: -8 }, badge: 'TEAM', greeting: 'Show me what breaks.',interaction: 'I assume something is broken until it survives a useful test.', topics: ['testing', 'bugs', 'failure', 'quality'] },
  { id: 'umbra', displayName: 'Umbra', role: 'The Unknown', style: 'umbra', spawn: { x: 18, z: -8 }, badge: 'TEAM', greeting: 'What did nobody ask?',interaction: 'I look for unknowns and questions that the rest of the team has not thought to ask yet.', topics: ['unknowns', 'questions', 'discovery'] },
];
